baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo-profile"

googleanalytics: UA-167646412-8
disqusShortname: gurusabarish
Paginate: 3

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal website. It is single page portfolio. It has blog."
  copyright: "2021"

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"

  # social
  name: "Hugo-profile"
  github: "https://github.com"
  linkedin: "https://linkedin.com"
  twitter: "https://twitter.com"
  instagram: "https://instagram.com"
  facebook: "https://facebook.com"

  # About
  profile_image: "/images/profile.webp"
  descripe_l1_person: "Hi, I'm Hugo-profile, a high performance theme for portfolio and blog. It's created and maintained by Gurusabarish who is web developer and machine learning enthusiast."
  descripe_l2_person: ""
  useresume: true
  resume: ""

  # Things I do
  usedothings: true
  Things:
    - logo: fab fa-python
      title: Python
      description: I build something beautiful using Python.

    - logo: fas fa-robot
      title: Machine learning
      description: I train robust models for various tasks.

    - logo: fab fa-html5
      title: Things for web
      description: I love to build things for web

  #Description for seo. If you want to show description in your blog post, let's make it true
  showdescription: false
