name = "Hugo Profile"
license = "MIT"
licenselink = "https://github.com/gurusabarish/hugo-profile/blob/master/LICENSE"
description = "A high performance hugo theme for personal portfolio and blog."
homepage = "https://hugo-profile.netlify.com"
tags = ["Responsive","Blog", "Portfolio", "Clean", "Fast", "Seo"]
min_version = "0.68.0"

[author]
  name = "Gurusabarish"
  homepage = "https://github.com/gurusabarish"
