baseURL: "https://example.com"
languageCode: "en-us"
title: "Hugo-profile"
theme: "hugo-profile"

googleanalytics: UA-xxxxxxxx-x
disqusShortname: yourdiscussshortname
Paginate: 3

taxonomies:
  tag: "tags"
  category: "categories"

params:
  favicon: "/images/hugo.png"
  description: "A hugh performance hugo theme for personal website. It is single page portfolio. It has blog, contact sections also. Contact is powered by formspree."
  disqus: ""
  copyright: "2020"

  # Background
  custombackground: false
  background: ""
  backimg: ""
  
  # Contact
  contact: true
  action: ""
  emailname: ""
  messagename: ""
  
  # Navbar Menus
  customMenus:
  - name: "Blog"
    Url: "/blog"
    
  # Home
  name: "Gurusabarish"
  profile: "/images/avatar.webp"
  github: "https://github.com/gurusabarish"
  linkedin: "https://linkedin.com/in/gurusabarish"
  twitter: "https://twitter.com/gurusabarishh"
  instagram: "https://instagram.com/gurusabarishh"

  # Do things 
  usedothings: true
  usedefaultlogos: true

  thing1: "Python"
  thing2: "Machine learning"
  thing3: "Things for web"
  thing1_des: "I build something beautiful using Python."
  thing2_des: "I train robust models for various tasks."
  thing3_des: "I love to build things for web."

  # About
  profile_image: "/images/gurusabarish.webp"
  descripe_l1_person: "Hi, I'm Gurusabarish, a passionate web developer and ML engineer. 
  I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
  descripe_l2_person: "This is just a example for about section. You can easily change with the help of cofig file."
  job: "your role"
  resume: ""
  
  #projects
  projects:
  - title: "Project name"
    image: "/images/project.webp"
    description:  "This is your description"
    secoundarylink: true
    secoundaryurlname: "Secoundary link"
    secoundaryurl: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"
  
  - title: "Project name"
    image: "/images/performance.webp"
    description:  "This is your description"
    secoundarylink: true
    secoundaryurlname: "Secoundary link"
    secoundaryurl: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"

  - title: "Project name"
    image: "/images/project.webp"
    description:  "This is your description"
    secoundarylink: true
    secoundaryurlname: "Secoundary link"
    secoundaryurl: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"

  - title: "Project name"
    image: "/images/performance.webp"
    description:  "This is your description"
    secoundarylink: true
    secoundaryurlname: "Secoundary link"
    secoundaryurl: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"

  - title: "Project name"
    image: "/images/project.webp"
    description:  "This is your description"
    secoundarylink: true
    secoundaryurlname: "Secoundary link"
    secoundaryurl: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"

  - title: "Project name"
    image: "/images/performance.webp"
    description:  "This is your description"
    secoundarylink: true
    secoundaryurlname: "Secoundary link"
    secoundaryurl: "https://github.com/gurusabarish/hugo-profile"
    sourceurl: "https://github.com/gurusabarish/hugo-profile"
  

Author:
  name: "Gurusabarish"
  website: "https://github.com/gurusabarish"
