baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"

Paginate: 3

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1

    #Dropdown menu
    - identifier: dropdown
      title: Example dropdown menu
      name: Dropdown
      weight: 2
    - identifier: dropdown1
      title: example dropdown 1
      name: example 1
      url: /#
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: example dropdown 2
      name: example 2
      url: /#
      parent: dropdown
      weight: 2

params:
  title: "Hugo Profile"
  description: Text about my cool site
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor: 
  #   secondaryTextColor:
  #   backgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor: 
  #     secondaryTextColor:
  #     backgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Hugo Profile."
    subtitle: "I build things for the web."
    content: "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
    button:
      enable: true
      name: "Get in touch"
      url: "#contact"


  # Achievements
  achievements:
    enable: true
    items:  
      - title: Competition winner
        content: We are developed a product which can help others.
        url: https://example.com
      - title: Competition winner
        content: We are developed a product which can help others.
        url: "!#"
      - title: Competition winner
        content: We are developed a product which can help others.
        url: "#"
      - title: Competition winner
        content: We are developed a product which can help others.
        url: "!#"
      - title: Competition winner
        content: We are developed a product which can help others.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Project 1
        content: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        image: /images/project.jpg
        featured:
          name: featured
          link: https://example.com
        badges:
          - "HTML"
          - "CSS"
          - "JavaScript"
        links:
          - icon: fa fa-envelope
            url: https://example.com
          - icon: fab fa-github
            url: https://example.com
          - icon: fab fa-twitter
            url: https://example.com
      - title: Project 2
        content: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        image: /images/project.jpg
        featured:
          name: featured
          link: https://example.com
        badges:
          - "HTML"
          - "CSS"
          - "JavaScript"
        links:
          - icon: fa fa-envelope
            url: https://example.com
          - icon: fab fa-github
            url: https://example.com
          - icon: fab fa-twitter
            url: https://example.com

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me

  footer:
    # recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com


