baseURL: "https://profile.gurusabarish.tech"
languageCode: "en-us"
title: "Hugo-profile"

googleanalytics: UA-167646412-8
disqusShortname: 
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # Navbar Menus
  customMenus:
    - name: "Blog"
      Url: "/blog"
    - name: "Version2"
      Url: "https://v2.profile.gurusabarish.tech"
    - name: "Version1"
      Url: "https://v1.profile.gurusabarish.tech"
  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Guru Sabarish"
  profession: "Full Stack Developer"
  github: "https://github.com/gurusabarish"
  linkedin: "https://linkedin.com/in/gurusabarish"
  twitter: "https://twitter.com/gurusabarishh"
  instagram: "https://instagram.com/gurusabarishh"
  facebook: "https://facebook.com/gurusabarish01"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Guru sabarish, a passionate web developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
  descripe_l2_person: "Check out my blogs [here](https://blog.gurusabarish.tech)"
  skills:
    - name: CSS
      percentage: 90
    - name: Django
      percentage: 85
    - name: Hugo
      percentage: 80
    - name: React JS
      percentage: 70

  # Experience
  disable_experience: false
  experience:
    - company: "Google"
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: false
  education:
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"

  # Projects
  disable_projects: false
  projects:
    - name: "Example project without details"
      img: /images/project.jpg
      githublink: "https://github.com/"
      featuredlink: "/"
      description: "Description of project"

  # Achievements
  disable_achievements: false
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "example@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
